# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Freds_2SampleTtest <- function(x1, x2) {
    .Call(`_FredsStatsPack_Freds_2SampleTtest`, x1, x2)
}

SigmaTau <- function(mu) {
    .Call(`_FredsStatsPack_SigmaTau`, mu)
}

Sum_Squares <- function(x) {
    .Call(`_FredsStatsPack_Sum_Squares`, x)
}

TukeysQ <- function(xi, xj, msw, n) {
    .Call(`_FredsStatsPack_TukeysQ`, xi, xj, msw, n)
}

rcpparma_hello_world <- function() {
    .Call(`_FredsStatsPack_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_FredsStatsPack_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_FredsStatsPack_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_FredsStatsPack_rcpparma_bothproducts`, x)
}

ttest_means <- function(y1, y2, n1, n2, mse) {
    .Call(`_FredsStatsPack_ttest_means`, y1, y2, n1, n2, mse)
}

